// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-demo/internal/dao/internal"
)

// internalDbTestsDao is internal type for wrapping internal DAO implements.
type internalDbTestsDao = *internal.DbTestsDao

// dbTestsDao is the data access object for table db_tests.
// You can define custom methods on it to extend its functionality as you wish.
type dbTestsDao struct {
	internalDbTestsDao
}

var (
	// DbTests is globally public accessible object for table db_tests operations.
	DbTests = dbTestsDao{
		internal.NewDbTestsDao(),
	}
)

// Fill with you ideas below.
